name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  database-setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ecommerce
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iamawriterbbHPharryPotter5378++
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Verify PostgreSQL Service
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for database to be ready..."
            sleep 5
          done
          echo "Database is ready!"

  backend-tests:
    runs-on: ubuntu-latest
    needs: database-setup
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Set Environment Variables
        run: echo "DATABASE_URL=postgresql://postgres:iamawriterbbHPharryPotter5378++@localhost:5432/ecommerce" >> $GITHUB_ENV

      - name: Build and Test Backend
        run: |
          npm run build
          npm test -- --passWithNoTests

  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npx jest --detectOpenHandles

  docker-compose-build:
    runs-on: ubuntu-latest
    needs: [frontend-tests, backend-tests]

    steps:
      - uses: actions/checkout@v4

      - name: Build and Run Docker Compose
        run: docker-compose up --build -d

      - name: Verify Docker Compose Services
        run: docker ps -a
